#!/usr/bin/env python3
"""
Merge a generated lab into an existing labs.json.

Usage example:
  # Copy current labs.json out of facilitator container
  docker cp facilitator:/usr/src/app/assets/exams/labs.json kubelingo/out/labs.base.json

  # Merge our generated lab entry
  python3 kubelingo/merge_labs.py --root kubelingo/out --lab-category ckad --lab-id 003 \
    --existing kubelingo/out/labs.base.json --out kubelingo/out/labs.merged.json

  # Copy merged file back into the container
  docker cp kubelingo/out/labs.merged.json facilitator:/usr/src/app/assets/exams/labs.json
"""

import argparse
import json
import os
import sys


def load_json(path: str) -> dict:
    with open(path, "r") as f:
        return json.load(f)


def dump_json(path: str, data: dict) -> None:
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="kubelingo/out", help="Kubelingo output root")
    ap.add_argument("--lab-category", required=True)
    ap.add_argument("--lab-id", required=True)
    ap.add_argument("--existing", required=True, help="Path to existing labs.json")
    ap.add_argument("--out", required=True, help="Path for merged labs.json output")
    args = ap.parse_args()

    root_abs = os.path.abspath(args.root)
    base_dir = os.path.join(root_abs, "facilitator", "assets", "exams", args.lab_category, args.lab_id)
    cfg_path = os.path.join(base_dir, "config.json")
    if not os.path.exists(cfg_path):
        print(f"ERROR: missing config.json for lab at {base_dir}", file=sys.stderr)
        print(
            "Hint: pass an absolute --root (e.g., /abs/path/to/CK-X/kubelingo/out) or run from the CK-X repo root.",
            file=sys.stderr,
        )
        return 2

    try:
        cfg = load_json(cfg_path)
    except Exception as e:
        print(f"ERROR: cannot read config.json: {e}", file=sys.stderr)
        return 2

    try:
        labs = load_json(args.existing)
    except Exception:
        labs = {"labs": []}

    labs.setdefault("labs", [])

    # Construct entry
    lab_id = cfg.get("lab") or f"{args.lab_category}-{args.lab_id}"
    entry = {
        "id": lab_id,
        "assetPath": f"assets/exams/{args.lab_category}/{args.lab_id}",
        "name": f"{args.lab_category.upper()} Practice Lab {args.lab_id}",
        "category": args.lab_category.upper(),
        "description": f"Practice lab generated by Kubelingo ({args.lab_category}-{args.lab_id})",
        "warmUpTimeInSeconds": 60,
        "difficulty": "medium",
    }

    # Remove prior with same id
    labs["labs"] = [l for l in labs["labs"] if l.get("id") != lab_id]
    labs["labs"].append(entry)

    dump_json(args.out, labs)
    print(f"Merged labs.json written to: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
